Coinpaprika\Model\Coin:
  access_type: public_method # defaults to property
  properties:
    id:
      type: string
    name:
      type: string
    symbol:
      type: string
    description:
      type: string
    rank:
      type: int
    new:
      type: boolean
      serialized_name: is_new
    active:
      type: boolean
      serialized_name: is_active
    tokenType:
      type: string
      serialized_name: type
    links:
      type: array
      serialized_name: links
